language: r

sudo: required

addons:
  apt:
    packages:
      - r-cran-rcpp

warnings_are_errors: false

dist: trusty

cache: packages

matrix:
  include:
  - r: release
  - r: devel

after_success:
  - Rscript -e 'library(covr); codecov()'
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    bash deploy.sh
