language: r
sudo: required
addons:
  apt:
    packages:
      - r-cran-rcpp
warnings_are_errors: false
dist: trusty
cache: packages
latex: false
r_build_args: --no-build-vignettes
matrix:
  include:
  - r: oldrel
  - r: release
    after_success: Rscript -e "covr::codecov()"
    before_cache: Rscript -e "remotes::install_github(repo = 'r-lib/pkgdown', ref = 'c33ea80')"
    deploy:
      provider: script
      script: Rscript -e "pkgdown::deploy_site_github(verbose = TRUE)"
      skip_cleanup: true
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^master|develop$
  - r: devel
